disease_detection/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.static import serve
from django.conf import settings
from django.conf.urls.static import static


from main.views import IndexView
# from dog_eye_detect.views import UploadView, FilesList, IndexView, UploadSuccessView, SelectPredFileView, SelectFileDelView, FileDeleteView


urlpatterns = [
    path('', IndexView.as_view()),
    path('admin/', admin.site.urls),
    path('index/', IndexView.as_view(), name='index'),
    path('dog_skin_detect/', include('dog_skin_detect.urls', namespace='dog_skin_detect')),
                                                        ## include 는 namespace
    path('dog_eye_detect/', include('dog_eye_detect.urls', namespace='dog_eye_detect')),
    path('bulletin/', include('bulletin.urls', namespace='bulletin')),

]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path('media/<path:path>', serve, {'document_root': settings.MEDIA_ROOT}),
    ] + urlpatterns


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dog_eye_detect/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from dog_eye_detect.views import FilesList, FileView, FileDeleteView, IndexView, Eye_Predict
from dog_eye_detect.views import SelectPredFileView, SelectFileDelView, FileDeleteView, UploadView , UploadSuccessView

app_name = 'dog_eye_detect'

urlpatterns = [
    path('', IndexView.as_view(), name='IndexView'),
    path('predict/', Eye_Predict.as_view(), name='APIpredict'),
    path('upload/', FileView.as_view(), name='APIupload'),
    path('delete/<int:pk>/', FileDeleteView.as_view(), name='APIdelete'),
        # Url to list all the files in the server
    path('files_list/', FilesList.as_view(), name='files_list'),
    path('filedelete/', SelectFileDelView.as_view(), name='file_delete'),
    path('delete_success/', FileDeleteView.as_view(), name='delete_success'),
    path('fileupload/', UploadView.as_view(), name='upload_file'),
    # Url to select a file for the predictions
    path('fileselect/', SelectPredFileView.as_view(), name='file_select'),

    # Url to select a file to be deleted and confirm the upload
    path('upload_success/', UploadSuccessView.as_view(), name='upload_success'),
    # path('display_image/<str:image_url>', views.display_image, name='display_image'),
    path('bulletin/', include('bulletin.urls', namespace='bulletin')),
        # Urls to upload the file and confirm the upload


]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/urls.py
from django.urls import path,include
from dog_skin_detect.views import IndexView

app_name = 'main'

urlpatterns = [
    path('', IndexView.as_view(), name='IndexView'),
    path('bulletin/', include('bulletin.urls', namespace='bulletin')),
]

dog_eye_detect/models.py
from django.db import models
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import post_delete


class XceptionImage(models.Model):
    file = models.FileField(null=True, blank=True, unique=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    path = models.FilePathField(path=settings.MEDIA_ROOT, default=settings.MEDIA_ROOT)
    id = models.BigAutoField(primary_key=True)

    class Meta:	
        unique_together = ['file', 'path']	


@receiver(post_delete, sender=XceptionImage)
def submission_delete(sender, instance, **kwargs):
    """
    파일 삭제 요청보내면 저장된 파일만 지우는 게 아니라 db 에 저장된 정보도 삭제해줌.
    삭제 요청 보내면 장고는 그냥 파일만 지우고, 기록은 안 지워줌.
    """
    instance.file.delete(False)

dog_eye_detect/forms.py
from django.forms import ModelForm
from dog_eye_detect.models import XceptionImage


class FileForm(ModelForm):
    """
    Creating a form that maps to the model: https://docs.djangoproject.com/en/2.2/topics/forms/modelforms/
    This form is used for the file upload.
    """
    class Meta:
        model = XceptionImage
        fields = ['file']

dog_eye_detect/views.py
import os
import requests
import numpy as np
from os import listdir
from os.path import join
from os.path import isfile
from googlesearch import search
from django.conf import settings
from django.shortcuts import render
from django.http import HttpResponseRedirect
from rest_framework import views, status
from django.views.generic import ListView
from rest_framework.response import Response
from django.views.generic import TemplateView
from rest_framework.parsers import FormParser
from django.views.generic.edit import CreateView
from rest_framework.parsers import MultiPartParser
from django.core.exceptions import ValidationError
from rest_framework.generics import get_object_or_404
from rest_framework.renderers import TemplateHTMLRenderer
from django.urls import reverse
from bs4 import BeautifulSoup
from dog_eye_detect.models import XceptionImage
from dog_eye_detect.serializes import FileSerializer
from django.db import IntegrityError
from django.contrib import messages

import keras
from keras.utils import load_img
from keras.utils import img_to_array
from keras.models import load_model

class IndexView(TemplateView):
    """
    웹 사이트 render view.
    """
    template_name = "dog_eye_detect/eye_detection.html"

    

class FilesList(ListView):
    """
    업로드한 파일을 확인할 수 있는 view.
    """
    model = XceptionImage
    template_name = "dog_eye_detect/files_list.html"
    context_object_name = "files_list"

    def show_files_list(request):
        files_list = XceptionImage.objects.all()
        return render(request, "dog_eye_detect/eye_detection.html", {"files_list": files_list})



class UploadView(CreateView):
    """
    파일을 서버에 업로드하는 view.
    """
    model = XceptionImage
    fields = ["file"]
    template_name = "dog_eye_detect/post_file.html"
    success_url = "upload_success/"

    def form_valid(self, form):
        file = form.instance.file
        path = form.instance.path
        try:
            if XceptionImage.objects.filter(file=file.name, path=path).exists():
                form.add_error("file", ValidationError("이미 업로드한 사진입니다!"))
                return super().form_invalid(form)
            else:
                return super().form_valid(form)
        except IntegrityError:
            messages.error(self.request, "A database error occurred.")
            return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["view_mode"] = "upload"  # Set the view_mode here
        context["files_list"] = XceptionImage.objects.all()
        return context



class UploadSuccessView(TemplateView):
    """
    업로드후 
    """
    template_name = "dog_eye_detect/upload_success.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["view_mode"] = "success"  # Set the view_mode here
        context["files_list"] = XceptionImage.objects.all()
        return context



class SelectPredFileView(TemplateView):
    """
    This view is used to select a file from the list of files in the server.
    After the selection, it will send the file to the server.
    The server will return the predictions.
    """

    template_name = "dog_eye_detect/select_file_predictions.html"
    parser_classes = FormParser
    queryset = XceptionImage.objects.all()

    def get_context_data(self, **kwargs):
        """
        This function is used to render the list of files in the MEDIA_ROOT in the html template.
        """
        context = super().get_context_data(**kwargs)
        media_path = settings.MEDIA_ROOT
        myfiles = [f for f in listdir(media_path) if isfile(join(media_path, f))]
        context["filename"] = myfiles
        return context



class SelectFileDelView(TemplateView):
    """
    This view is used to select a file from the list of files in the server.
    After the selection, it will send the file to the server.
    The server will then delete the file.
    """
    template_name = "dog_eye_detect/select_file_deletion.html"
    parser_classes = FormParser
    queryset = XceptionImage.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        media_path = settings.MEDIA_ROOT
        myfiles = [f for f in listdir(media_path) if isfile(join(media_path, f))]
        primary_key_list = []
        for value in myfiles:
            primary_key = XceptionImage.objects.filter(file=value).values_list("pk", flat=True)
            if primary_key.exists():  # Check if the queryset is not empty
                primary_key_list.append(primary_key.first())  # .first() will get the first (and only) value from the queryset
            else:
                primary_key_list.append(None)  # Append None if no primary key exists

        file_and_pk = list(zip(myfiles, primary_key_list))
        context["filename"] = file_and_pk
        return context



class FileDeleteView(views.APIView):
    """
    This class contains the method to delete a file interacting directly with the API.
    DELETE requests are accepted.
    """
    model = XceptionImage
    fields = ['file']
    template_name = "dog_eye_detect/select_file_deletion.html"
    success_url = '/delete_success/'

    def post(self, request, pk):   # Add 'pk' as an argument
        """
        This method is used delete a file.
        """
        delete_action = get_object_or_404(XceptionImage, pk=pk).delete()  # Use 'pk' directly
        try:
            # after successful delete, render a success page
            return render(request, 'dog_eye_detect/delete_success.html', {'pk': delete_action})
        except ValueError as err:
            return Response(str(err), status=status.HTTP_400_BAD_REQUEST)




class FileView(views.APIView):
    """
    This class contains the method to upload a file interacting directly with the API.
    POST requests are accepted.
    """
    parser_classes = (MultiPartParser, FormParser)
    queryset = XceptionImage.objects.all()

    # def post(request):
    #     """
    #     This method is used to Make POST requests to save a file in the media folder
    #     """
    #     file_serializer = FileSerializer(data=request.data)
    #     if file_serializer.is_valid():
    #         file_serializer.save()
    #         response = Response(file_serializer.data, status=status.HTTP_201_CREATED)
    #     else:
    #         response = Response(file_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
    #     return response


    # @staticmethod
    def post(self, request):
        file_name = request.data.get("file").name  # Extract file name
        if self.check_file_exists(file_name) or self.check_object_exists(file_name):
            return Response({"error": "File already exists"}, status=status.HTTP_400_BAD_REQUEST)

        file_serializer = FileSerializer(data=request.data)

        ## 업로드 후 API site 나오는 건 여기 response 를 httpsResponse 로 바꿔서 render 해주면 될듯?
        """
        if file_serializer.is_valid():
            file_serializer.save()
            return Response(file_serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(file_serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        """

        if file_serializer.is_valid():
            file_serializer.save()
            return HttpResponseRedirect(reverse("dog_eye_detect:upload_success"))
        
        else:
            return Response(file_serializer.errors, status=status.HTTP_400_BAD_REQUEST)


    # @staticmethod
    def check_file_exists(self, file_name):
        """
        This method will receive as input the file the user wants to store
        on the server and check if a file with this name is physically in
        the server folder.
        If this function returns True, the user should not be able to save the
        file (or at least he/she should be prompted with a message saying that
        the file is already existing)
        """
        check = os.path.isfile(os.path.join(settings.MEDIA_ROOT, file_name))
        return check

    # @staticmethod
    def check_object_exists(self, file_name):
        """
        This method will receive as input the file the user wants to store
        on the server and check if an object with that name exists in the
        database.
        If this function returns True, the user should not be able to save the
        file (or at least he/she should be prompted with a message saying that
        the file is already existing)
        """
        check = XceptionImage.objects.filter(file=file_name).exists()
        return check


def search(query, num_results):
    search_url = f"https://www.google.com/search?q={query}&num={num_results}"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36"
    }
    response = requests.get(search_url, headers=headers)
    soup = BeautifulSoup(response.text, "html.parser")
    search_results = []

    for result in soup.find_all("div", class_="yuRUbf"):
        link = result.find("a")
        url = link["href"]
        search_results.append(url)

    return search_results

class Eye_Predict(views.APIView):
    """
    학습한 모델의 가중치를 불러오고 예측을 진행하는 코드, rest framework 를 이용해서 yolov8 api 를 만듦.
    """

    template_name = "dog_eye_detect/eye_detection.html"
    renderer_classes = [TemplateHTMLRenderer]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)

        # Load your model here
        self.model = load_model("/Users/csb01/Desktop/dog_eye_disease_xception_epoch_100_true.h5")

    def post(self, request):
        """
        This method is used to make predictions on image files
        loaded with FileView.post
        """
        filename = request.POST.getlist("file_name").pop()
        filepath = str(os.path.join(settings.MEDIA_ROOT, filename))

        height = width = 224
        
        channel = 3

templates/dog_eye_detect/delete_success.html
{% extends "dog_eye_detect/eye_detection.html" %}

{% block content %}
    <h5>
        파일이 성공적으로 삭제되었습니다!
    </h5>

{% endblock %}

templates/dog_eye_detect/display_output.html
<!-- display_image.html -->
{% extends "dog_eye_detect/eye_detection.html" %}

{% block content %}

<article>
  <p>
    질병이 걱정돼 예방하고 싶으신가요? 저희가 도움이 될지도 모르는 몇 가지 검색 결과를 준비해봤어요! 
  </p>
    <ul>
        {% for result in search_results %}
          <li><a href="{{ result }}">{{ result }}</a></li>
        {% endfor %}
    </ul>
</article>

{% endblock %}

templates/dog_eye_detect/eye_detection.html
<!DOCTYPE HTML>
<!--
	Forty by HTML5 UP
	html5up.net | @ajlkn
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	{% load static %}
	<head>
		<title>프레로 독 - 반려견 질병 진단 서비스</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<link rel="stylesheet" href="{% static 'css/main.css' %}" />
		<noscript><link rel="stylesheet" href="{% static 'css/noscript.css' %}" /></noscript>
	</head>
	<body class="is-preload">

		<!-- Wrapper -->
			<div id="wrapper">

				<!-- Header -->
				<!-- Note: The "styleN" class below should match that of the banner element. -->
					<header id="header" class="alt style2">
						<a href="/index/" class="logo"><strong>프레로</strong> <span>독</span></a>
						<nav>
							<a href="#menu">메뉴</a>
						</nav>
					</header>

				<!-- Menu -->
					<nav id="menu">
						<ul class="links">
							<li><a href="/index/">홈페이지</a></li>
							<li><a href="/dog_eye_detect/">안구 질환 확인</a></li>
							<li><a href="/dog_skin_detect/">피부 질환 확인</a></li>
							<li><a href="/bulletin/">질문하기</a></li>
							<!-- <li><a href="elements.html">건강 식품</a></li>
							<li><a href="elements.html">우리에 대해</a></li> -->
						</ul>
						<!-- <ul class="actions stacked">
							<li><a href="#" class="button primary fit">회원가입</a></li>
							<li><a href="#" class="button fit">로그인</a></li>
							<li><a href="#" class="button fit">아이디 / 비밀번호 찾기</a></li>
						</ul> -->
					</nav>

				<!-- Banner -->
				<!-- Note: The "styleN" class below should match that of the header element. -->
					<section id="banner" class="style2">
						<div class="inner">
							<span class="image">
								<img src="{% static 'image/detect_banner.png' %}" alt="" />
							</span>
							<header class="major">
								<h1>안구 질환 확인하기</h1>
							</header>
							<div class="content">
								<p>
									직접 촬영하신 사진을 가이드라인에 맞춰서 업로드 해주세요.
									<br>
									잠시 뒤에 결과를 확인하실 수 있습니다.
								</p>
							</div>
						</div>
					</section>

				<!-- Main -->
					<div id="main">

						<!-- One -->
							<section id="one">
								<div class="inner">
									<header class="">
										<h2>올바르게 사진 올리는 방법</h2>
									</header>
									<!--
										<p>
											
										</p>
									-->
								</div>
							</section>

							<section id="two" class="spotlights">
								<section>
									<a href="#" class="image">
										<img src="{% static 'image/right_eye_example.jpg' %}" alt="" data-position="center center" />
									</a>
									<div class="content">
										<div class="inner">
											<header class="major">
												<h3>올바른 예시</h3>
											</header>
											<p>
												예시 사진 처럼 눈을 최대한 가까이 찍어주세요!
											</p>
											<ul class="actions">
												<!--
													<li><a href="generic.html" class="button">Learn more</a></li>
												-->
											</ul>
										</div>
									</div>
								</section>
								<section>
									<a href="#" class="image">
										<img src="{% static 'image/wrong_eye_example.jpeg' %}" alt="" data-position="top center" />
									</a>
									<div class="content">
										<div class="inner">
											<header class="major">
												<h3>이렇게는 안돼요!</h3>
											</header>
											<p>
												눈을 제외한 다른 부분이 가능하면 나오지 않도록 해주세요.
											</p>
											<ul class="actions">
												<!--
													<li><a href="generic.html" class="button">Learn more</a></li>
												-->
											</ul>
										</div>
									</div>
								</section>
								<section>
									<a href="#" class="image">
										<img src="{% static 'image/reject.jpg' %}" alt="" data-position="25% 25%" />
									</a>
									<div class="content">
										<div class="inner">
											<header class="major">
												<h3>결과가 믿음이 가지 않아요!</h3>
											</header>
											<p>
												프레로독은 결정에 도움을 드리는 것뿐이고, 언제나 최종 판단은 전문의의 진료를 받으셔야 합니다.
											</p>
											<ul class="actions">
												<!--
													<li><a href="generic.html" class="button">Learn more</a></li>
												-->
											</ul>
										</div>
									</div>
								</section>
							</section>

							<!-- Three -->
							<section id="three">
								<div class="inner">
									<header class="major">
										<h2>사진 업로드</h2>
									</header>
									<p>
										이제 올바른 방법으로 사진을 첨부해주시고, 잠시만 기다려주세요!
										<br>
										금방 결과를 확인하실 수 있을거에요.
									</p>


									<ul class="actions">
										<!-- 파일 첨부 기능 구현-->
										<label class="button next" for="input-file">파일 첨부</label>
										<form action="{% url 'dog_eye_detect:APIupload' %}" method="post" enctype="multipart/form-data">
											{% csrf_token %}
											<input type="file" name="file" id="input-file" style="display:none">
											
											<input type="submit" value="파일 업로드">
										</form>
										<li><a href="{% url 'dog_eye_detect:files_list' %}" class="button next">내가 올린 파일 보기</a></li>
										<li><a href="{% url 'dog_eye_detect:file_delete' %}" class="button next">내가 올린 파일 지우기</a></li>	
										<li><a href="{% url 'dog_eye_detect:file_select' %}" class="button next">예측하기</a></li>
									</ul>
									<span id="file-name"></span>
									<!-- 첨부한 파일 이름 확인 -->
									<script>
										document.getElementById('input-file').addEventListener('change', function() {
											var fileName = this.files[0].name;
											document.getElementById('file-name').textContent = fileName;
										});
									</script>
									
										{% block content %}
										{% endblock %}

								</div>
							</section>

					</div>

				
				<!-- Contact -->
				<!--

					<section id="contact">
						<div class="inner">
						<section>
							<form method="post" action="#">
								<div class="fields">
									<div class="field half">
										<label for="name">성함</label>
										<input type="text" name="name" id="name" />
									</div>
									<div class="field half">
										<label for="email">E-mail</label>
										<input type="text" name="email" id="email" />
									</div>
									<div class="field">
										<label for="message">보내실 말씀</label>
										<textarea name="message" id="message" rows="6"></textarea>
									</div>
								</div>
								<ul class="actions">
									<li><input type="submit" value="메시지 보내기" class="primary" /></li>
									<li><input type="reset" value="지우기" /></li>
								</ul>
							</form>
						</section>
						<section class="split">
							<section>
								<div class="contact-method">
									<span class="icon solid alt fa-envelope"></span>
									<h3>E-mail</h3>
									<a href="#">flfsk12@gmail.com</a>
								</div>
							</section>
							<section>
								<div class="contact-method">
									<span class="icon solid alt fa-phone"></span>
									<h3>연락처</h3>
									<span>010-0000-0000</span>
								</div>
							</section>
							<section>
								<div class="contact-method">
									<span class="icon solid alt fa-home"></span>
									<h3>주소</h3>
									<span>광주광역시<br />
										북구 용봉로 77<br />
										전남대학교</span>
									</div>
								</section>
							</section>
						</div>
					</section>
					-->
					
					<!-- Footer -->
					<footer id="footer">
						<div class="inner">
							<!-- <ul class="icons">
								<li><a href="#" class="icon brands alt fa-twitter"><span class="label">Twitter</span></a></li>
								<li><a href="#" class="icon brands alt fa-facebook-f"><span class="label">Facebook</span></a></li>
								<li><a href="#" class="icon brands alt fa-instagram"><span class="label">Instagram</span></a></li>
								<li><a href="#" class="icon brands alt fa-github"><span class="label">GitHub</span></a></li>
								<li><a href="#" class="icon brands alt fa-linkedin-in"><span class="label">LinkedIn</span></a></li>
							</ul> -->
							<ul class="copyright">
								<li>&copy; Prero Dog </li><li>Design: <a href="https://html5up.net">HTML5 UP</a></li>
							</ul>
						</div>
					</footer>

			</div>

		<!-- Scripts -->
		<script src="{% static 'js/jquery.min.js' %}"></script>
		<script src="{% static 'js/jquery.scrolly.min.js' %}"></script>
		<script src="{% static 'js/jquery.scrollex.min.js' %}"></script>
		<script src="{% static 'js/browser.min.js' %}"></script>
		<script src="{% static 'js/breakpoints.min.js' %}"></script>
		<script src="{% static 'js/util.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>

	</body>
</html>

templates/dog_eye_detect/files_list.html
{% extends "dog_eye_detect/eye_detection.html" %}

{% block content %}

{% for file_model in files_list %}

<p>{{ file_model.file.name }}</p>

{%endfor%}

{% endblock %}

templates/dog_eye_detect/post_file.html
{% extends "dog_eye_detect/eye_detection.html" %}

{% block content %}
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Upload file</button>
    </form>
{% endblock %}

templates/dog_eye_detect/select_file_deletion.html
{% extends "dog_eye_detect/eye_detection.html" %}

{% block content %}
<h5>삭제할 파일을 선택해주세요:</h5>
{% for myfile, pk_value in filename %}
    <p> - {{ myfile }}</p>
    {% if pk_value %}  <!-- Only display the form if pk_value is not None -->
        <form action=" {% url 'dog_eye_detect:APIdelete' pk=pk_value %} " method="post">
            {% csrf_token %}
            <input type="submit" value="Delete">
        </form>
    {% endif %}
{% endfor %}
{% endblock %}

templates/dog_eye_detect/select_file_predictions.html
{% extends "dog_eye_detect/eye_detection.html" %}

{% block content %}
    <form action="{% url 'dog_eye_detect:APIpredict' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <h5>예측을 원하는 파일을 선택해 주세요!</h5>
        <h5>파일 이름을 누르시면 이미지 파일을 확인하실 수 있습니다.</h5>
        {% for myfile in filename %}
        <input id="selection_{{ forloop.counter }}" type="radio" name="file_name" value="{{ myfile }}">
        <label for="selection_{{ forloop.counter }}">
            <a href="/media/{{ myfile }}">{{ myfile }}</a>
        </label>
        <br>
        {% endfor %}
        <br>
        <button type="submit" class="btn btn-primary">예측하기</button>
    </form>
{% endblock %}

templates/dog_eye_detect/upload_success.html
{% extends "dog_eye_detect/eye_detection.html" %}

{% block content %}
    <h5>
        파일이 성공적으로 업로드 되었습니다!
    </h5>
{% endblock %}